name: Build and publish

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e ".[dev]"
      - name: Validate type annotations
        run: |
          mypy --strict prefixdate
      - name: Run tests
        run: |
          pytest --cov=prefixdate tests/
      - name: Build a distribution
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: dist/
